version: 1.0.{build}
build:
  verbosity: minimal
deploy:
- provider: GitHub
  tag: v1.0
  release: v1.0
  auth_token:
    secure: XBjMjEzRrAS6KJVXRIHqcfvHbLma63NHtO0y1gCUgVrpwLe6M/ww3NL5ghhtQnzh
  prerelease: true